name: Flujo de trabajo para ejecutar los test P5
on:
  workflow_dispatch:
  push:
    branches: [ desarrollo ]
  pull_request:
    branches: [ desarrollo ]
  schedule:
    - cron: '1 23 * * 0-4'
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
<<<<<<< HEAD
      - name: Construyendo el codigo
=======
      - name: Construyendo el código
>>>>>>> ca3271e7689adf41a05e5abdfac06532fd5f6213
        run: |
          chmod +x gradlew        
          ./gradlew assemble
  Test:
    runs-on: ubuntu-latest
    needs: Build
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
<<<<<<< HEAD
      - name: Probando el codigo
=======
      - name: Probando el código
>>>>>>> ca3271e7689adf41a05e5abdfac06532fd5f6213
        run: |
          chmod +x gradlew        
          ./gradlew test
